-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bids
(
    bid_id uuid NOT NULL DEFAULT uuidv7(),
    bid_thread_id uuid NOT NULL,
    bid_creator_id uuid NOT NULL,
    amount integer NOT NULL,
    creation_time timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT bids_pkey PRIMARY KEY (bid_id)
);

CREATE TABLE IF NOT EXISTS public.game_gamemodes
(
    game_id uuid NOT NULL,
    gamemode_id uuid NOT NULL,
    CONSTRAINT game_gamemodes_pkey PRIMARY KEY (game_id, gamemode_id)
);

CREATE TABLE IF NOT EXISTS public.gamemodes
(
    gamemode_id uuid NOT NULL DEFAULT uuidv7(),
    gamemode_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT gamemode_pkey PRIMARY KEY (gamemode_id)
);

CREATE TABLE IF NOT EXISTS public.games
(
    game_id uuid NOT NULL DEFAULT uuidv7(),
    host_id uuid NOT NULL,
    creation_time timestamp with time zone NOT NULL DEFAULT now(),
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    CONSTRAINT games_pkey PRIMARY KEY (game_id)
);

CREATE TABLE IF NOT EXISTS public.hosts
(
    host_id uuid NOT NULL DEFAULT uuidv7(),
    user_role_id uuid NOT NULL,
    host_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(100) NOT NULL,
    CONSTRAINT hosts_pkey PRIMARY KEY (host_id),
    CONSTRAINT hosts_host_name_key UNIQUE (host_name)
);

CREATE TABLE IF NOT EXISTS public.listings
(
    listing_id uuid NOT NULL DEFAULT uuidv7(),
    seller_id uuid NOT NULL,
    price integer NOT NULL,
    creation_time timestamp with time zone NOT NULL DEFAULT now(),
    listing_state integer NOT NULL,
    cards integer[] NOT NULL,
    CONSTRAINT listings_pkey PRIMARY KEY (listing_id)
);

CREATE TABLE IF NOT EXISTS public.game_phases
(
    game_phase_id uuid NOT NULL DEFAULT uuidv7(),
    phase_id uuid NOT NULL,
    game_id uuid NOT NULL,
    gamemode_id uuid NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    CONSTRAINT game_phases_pkey PRIMARY KEY (game_phase_id)
);

CREATE TABLE IF NOT EXISTS public.players
(
    player_id uuid NOT NULL DEFAULT uuidv7(),
    age_group_id uuid NOT NULL,
    gender_id uuid NOT NULL,
    country_of_residence_id uuid NOT NULL,
    country_of_birth_id uuid NOT NULL,
    CONSTRAINT players_pkey PRIMARY KEY (player_id)
);

CREATE TABLE IF NOT EXISTS public.transactions
(
    transaction_id uuid NOT NULL DEFAULT uuidv7(),
    phase_id uuid NOT NULL,
    game_id uuid NOT NULL,
    transaction_type integer NOT NULL,
    creation_time timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.listing_buys
(
    transaction_id uuid NOT NULL,
    listing_id uuid NOT NULL,
    buyer_id uuid NOT NULL,
    CONSTRAINT listing_buys_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.buy_request_bid_accepts
(
    transaction_id uuid NOT NULL,
    bid_id uuid NOT NULL,
    buy_request_id uuid NOT NULL,
    CONSTRAINT buy_request_bid_accepts_pk PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.buy_requests
(
    buy_request_id uuid NOT NULL DEFAULT uuidv7(),
    requester_id uuid NOT NULL,
    offered_price integer NOT NULL,
    creation_time timestamp with time zone NOT NULL DEFAULT now(),
    requested_cards integer[] NOT NULL,
    CONSTRAINT buy_requests_pkey PRIMARY KEY (buy_request_id)
);

CREATE TABLE IF NOT EXISTS public.buy_request_accepts
(
    transaction_id uuid NOT NULL,
    buy_request_id uuid NOT NULL,
    request_accepter_id uuid NOT NULL,
    CONSTRAINT buy_request_accepts_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.authorization_accounts
(
    authorization_account_id uuid NOT NULL DEFAULT uuidv7(),
    game_id uuid NOT NULL,
    player_id uuid,
    user_role_id uuid NOT NULL,
    access_name character varying(32) NOT NULL,
    password_hash character varying(100) NOT NULL,
    PRIMARY KEY (authorization_account_id)
);

CREATE TABLE IF NOT EXISTS public.donations
(
    transaction_id uuid NOT NULL,
    donator_id uuid NOT NULL,
    donation_amount integer NOT NULL,
    CONSTRAINT donations_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.bid_threads
(
    bid_thread_id uuid NOT NULL DEFAULT uuidv7(),
    thread_initiator_id uuid NOT NULL,
    thread_owner_id uuid NOT NULL,
    creation_time timestamp with time zone NOT NULL DEFAULT now(),
    status integer NOT NULL,
    CONSTRAINT bid_threads_pkey PRIMARY KEY (bid_thread_id)
);

CREATE TABLE IF NOT EXISTS public.players_game_data
(
    game_data_id uuid NOT NULL DEFAULT uuidv7(),
    player_id uuid NOT NULL,
    gamemode_id uuid NOT NULL,
    start_balance integer NOT NULL,
    start_cards integer[] NOT NULL,
    end_balance integer NOT NULL,
    end_points integer NOT NULL,
    CONSTRAINT players_game_data_pkey PRIMARY KEY (game_data_id)
);

CREATE TABLE IF NOT EXISTS public.genders
(
    gender_id uuid NOT NULL DEFAULT uuidv7(),
    gender_description character varying(20) NOT NULL,
    PRIMARY KEY (gender_id)
);

CREATE TABLE IF NOT EXISTS public.countries
(
    country_id uuid NOT NULL DEFAULT uuidv7(),
    country_name character varying(50) NOT NULL,
    country_abbreviation character varying(10) NOT NULL,
    PRIMARY KEY (country_id)
);

CREATE TABLE IF NOT EXISTS public.age_groups
(
    age_group_id uuid NOT NULL DEFAULT uuidv7(),
    minimum_age integer NOT NULL,
    maximum_age integer NOT NULL,
    description character varying(20) NOT NULL,
    PRIMARY KEY (age_group_id)
);

CREATE TABLE IF NOT EXISTS public.sumsy_players_game_data
(
    game_data_id uuid NOT NULL,
    total_money_correction integer NOT NULL,
    CONSTRAINT sumsy_players_game_data_pkey PRIMARY KEY (game_data_id)
);

CREATE TABLE IF NOT EXISTS public.debt_players_game_data
(
    game_data_id uuid NOT NULL,
    dept integer NOT NULL,
    interest_remainder integer NOT NULL,
    is_bank boolean NOT NULL,
    end_dept integer NOT NULL,
    end_interest_remainder integer NOT NULL,
    CONSTRAINT debt_players_game_data_pkey PRIMARY KEY (game_data_id)
);

CREATE TABLE IF NOT EXISTS public.loans
(
    transaction_id uuid NOT NULL,
    loan_taker uuid NOT NULL,
    bank_player uuid NOT NULL,
    loan_amount integer NOT NULL,
    CONSTRAINT loans_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.dept_payments
(
    transaction_id uuid NOT NULL,
    payer_id uuid NOT NULL,
    bank_player_id uuid NOT NULL,
    payment_amount uuid NOT NULL,
    CONSTRAINT dept_payments_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.interest_payments
(
    transaction_id uuid NOT NULL,
    payer_id uuid NOT NULL,
    bank_player_id uuid NOT NULL,
    payment_amount integer NOT NULL,
    CONSTRAINT interest_payments_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.phases
(
    phase_id uuid NOT NULL DEFAULT uuidv7(),
    phase_name character varying(25) NOT NULL,
    CONSTRAINT phases_pkey PRIMARY KEY (phase_id)
);

CREATE TABLE IF NOT EXISTS public.listing_bid_threads
(
    listing_id uuid NOT NULL,
    bid_thread_id uuid NOT NULL,
    CONSTRAINT listing_bid_threads_pkey PRIMARY KEY (listing_id, bid_thread_id)
);

CREATE TABLE IF NOT EXISTS public.buy_request_bid_threads
(
    buy_request_id uuid NOT NULL,
    bid_thread_id uuid NOT NULL,
    CONSTRAINT buy_request_bid_threads_pkey PRIMARY KEY (buy_request_id, bid_thread_id)
);

CREATE TABLE IF NOT EXISTS public.listing_bid_accepts
(
    transaction_id uuid NOT NULL,
    bid_id uuid NOT NULL,
    listing_id uuid NOT NULL,
    CONSTRAINT listing_bid_accepts_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_role_id uuid NOT NULL DEFAULT uuidv7(),
    user_role_name character varying(20) NOT NULL,
    PRIMARY KEY (user_role_id)
);

ALTER TABLE IF EXISTS public.bids
    ADD CONSTRAINT bids_bid_thread_id_fkey FOREIGN KEY (bid_thread_id)
    REFERENCES public.bid_threads (bid_thread_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.bids
    ADD CONSTRAINT bids_bid_creator_id_fkey FOREIGN KEY (bid_creator_id)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.game_gamemodes
    ADD CONSTRAINT gamemodes_gamemode_id_fkey FOREIGN KEY (gamemode_id)
    REFERENCES public.gamemodes (gamemode_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.game_gamemodes
    ADD CONSTRAINT games_game_id_fkey FOREIGN KEY (game_id)
    REFERENCES public.games (game_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.games
    ADD CONSTRAINT hosts_host_id_fkey FOREIGN KEY (host_id)
    REFERENCES public.hosts (host_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.hosts
    ADD CONSTRAINT hosts_user_role_id_fkey FOREIGN KEY (user_role_id)
    REFERENCES public.user_roles (user_role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.listings
    ADD CONSTRAINT listings_seller_id_fkey FOREIGN KEY (seller_id)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.game_phases
    ADD CONSTRAINT game_phases_game_id_fkey FOREIGN KEY (game_id)
    REFERENCES public.games (game_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.game_phases
    ADD CONSTRAINT game_phases_phase_id_fkey FOREIGN KEY (phase_id)
    REFERENCES public.phases (phase_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.game_phases
    ADD CONSTRAINT game_phases_gamemode_id_fkey FOREIGN KEY (gamemode_id)
    REFERENCES public.gamemodes (gamemode_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.players
    ADD CONSTRAINT players_age_group_id_fkey FOREIGN KEY (age_group_id)
    REFERENCES public.age_groups (age_group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.players
    ADD CONSTRAINT players_gender_id_fkey FOREIGN KEY (gender_id)
    REFERENCES public.genders (gender_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.players
    ADD CONSTRAINT players_country_of_residence_id_fkey FOREIGN KEY (country_of_residence_id)
    REFERENCES public.countries (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.players
    ADD CONSTRAINT players_country_of_birth_id_fkey FOREIGN KEY (country_of_birth_id)
    REFERENCES public.countries (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT transactions_game_phase_id_fkey FOREIGN KEY (phase_id)
    REFERENCES public.game_phases (game_phase_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.listing_buys
    ADD CONSTRAINT listing_buys_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES public.transactions (transaction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.listing_buys
    ADD CONSTRAINT listing_buys_listing_id_fkey FOREIGN KEY (listing_id)
    REFERENCES public.listings (listing_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.listing_buys
    ADD CONSTRAINT listing_buys_buyer_id_fkey FOREIGN KEY (buyer_id)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.buy_request_bid_accepts
    ADD CONSTRAINT buy_request_bid_accepts_bid_id_fkey FOREIGN KEY (bid_id)
    REFERENCES public.bids (bid_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.buy_request_bid_accepts
    ADD CONSTRAINT buy_request_bid_accepts_buy_request_id_fkey FOREIGN KEY (buy_request_id)
    REFERENCES public.buy_requests (buy_request_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.buy_request_bid_accepts
    ADD CONSTRAINT buy_request_bid_accepts_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES public.transactions (transaction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.buy_requests
    ADD CONSTRAINT buy_requests_requester_id FOREIGN KEY (requester_id)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.buy_request_accepts
    ADD CONSTRAINT buy_request_accepts_buy_request_id_fkey FOREIGN KEY (buy_request_id)
    REFERENCES public.buy_requests (buy_request_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.buy_request_accepts
    ADD CONSTRAINT buy_request_accepts_request_accepter_id_fkey FOREIGN KEY (request_accepter_id)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.buy_request_accepts
    ADD CONSTRAINT buy_request_accepts_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES public.transactions (transaction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.authorization_accounts
    ADD CONSTRAINT authorization_accounts_game_id_fkey FOREIGN KEY (game_id)
    REFERENCES public.games (game_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.authorization_accounts
    ADD CONSTRAINT authorization_accounts_user_role_id_fkey FOREIGN KEY (user_role_id)
    REFERENCES public.user_roles (user_role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.authorization_accounts
    ADD CONSTRAINT authorization_accounts_player_id_fkey FOREIGN KEY (player_id)
    REFERENCES public.players (player_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.donations
    ADD CONSTRAINT donations_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES public.transactions (transaction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.donations
    ADD CONSTRAINT donations_donator_id_fkey FOREIGN KEY (donator_id)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.bid_threads
    ADD CONSTRAINT bid_threads_thread_initiator_id FOREIGN KEY (thread_initiator_id)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.bid_threads
    ADD CONSTRAINT bid_threads_thread_owner_id FOREIGN KEY (thread_owner_id)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.players_game_data
    ADD CONSTRAINT players_game_data_player_id_fkey FOREIGN KEY (player_id)
    REFERENCES public.players (player_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.players_game_data
    ADD CONSTRAINT players_game_data_gamemode_id_fkey FOREIGN KEY (gamemode_id)
    REFERENCES public.gamemodes (gamemode_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sumsy_players_game_data
    ADD CONSTRAINT sumsy_players_game_data_game_data_id_fkey FOREIGN KEY (game_data_id)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.debt_players_game_data
    ADD CONSTRAINT debt_players_game_data_game_data_id_fkey FOREIGN KEY (game_data_id)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.loans
    ADD CONSTRAINT loans_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES public.transactions (transaction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.loans
    ADD CONSTRAINT loans_loan_taker_id_fkey FOREIGN KEY (loan_taker)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.loans
    ADD CONSTRAINT loans_bank_player_id_fkey FOREIGN KEY (bank_player)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_payments
    ADD CONSTRAINT dept_payments_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES public.transactions (transaction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_payments
    ADD CONSTRAINT dept_payments_payer_id_fkey FOREIGN KEY (payer_id)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_payments
    ADD CONSTRAINT dept_payments_bank_player_id_fkey FOREIGN KEY (bank_player_id)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.interest_payments
    ADD CONSTRAINT interest_payments_payer_id_fkey FOREIGN KEY (payer_id)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.interest_payments
    ADD CONSTRAINT interest_payments_bank_player_id_fkey FOREIGN KEY (bank_player_id)
    REFERENCES public.players_game_data (game_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.interest_payments
    ADD CONSTRAINT interest_payments_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES public.transactions (transaction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.listing_bid_threads
    ADD CONSTRAINT listing_bid_threads_listing_id_fkey FOREIGN KEY (listing_id)
    REFERENCES public.listings (listing_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.listing_bid_threads
    ADD CONSTRAINT listing_bid_threads_bid_thread_id_fkey FOREIGN KEY (bid_thread_id)
    REFERENCES public.bid_threads (bid_thread_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.buy_request_bid_threads
    ADD CONSTRAINT buy_request_bid_threads_buy_request_id_fkey FOREIGN KEY (buy_request_id)
    REFERENCES public.buy_requests (buy_request_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.buy_request_bid_threads
    ADD CONSTRAINT buy_request_bid_threads_bid_thread_id_fkey FOREIGN KEY (bid_thread_id)
    REFERENCES public.bid_threads (bid_thread_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.listing_bid_accepts
    ADD CONSTRAINT listing_bid_accepts_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES public.transactions (transaction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.listing_bid_accepts
    ADD CONSTRAINT listing_bid_accepts_bid_id_fkey FOREIGN KEY (bid_id)
    REFERENCES public.bids (bid_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.listing_bid_accepts
    ADD CONSTRAINT listing_bid_accepts_listing_id_fkey FOREIGN KEY (listing_id)
    REFERENCES public.listings (listing_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;